import { Groq } from 'groq-sdk';

interface AnalysisOptions {
  prNumber?: string;
  repo?: string;
  files?: string[];
}

export class ReasoningEngine {
  private client: Groq;

  constructor() {
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
      throw new Error('GROQ_API_KEY environment variable is not set');
    }
    this.client = new Groq({ apiKey });
  }

  async analyzeCode(options: AnalysisOptions): Promise<string> {
    const prompt = this.buildAnalysisPrompt(options);
    
    const message = await this.client.messages.create({
      model: 'mixtral-8x7b-32768',
      max_tokens: 2048,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    });

    const content = message.content[0];
    if (content.type === 'text') {
      return this.formatAnalysisOutput(content.text);
    }
    throw new Error('Unexpected response format');
  }

  async reviewPR(options: { prNumber?: string; repo?: string }): Promise<string> {
    const prompt = `
You are a senior code reviewer. Analyze this pull request and provide:
1. Summary of changes
2. Code quality assessment
3. Potential issues or improvements
4. Security considerations
5. Performance implications
6. Overall recommendation

Repository: ${options.repo || 'unknown'}
PR Number: ${options.prNumber || 'unknown'}

Provide thoughtful, constructive feedback.
    `;

    const message = await this.client.messages.create({
      model: 'mixtral-8x7b-32768',
      max_tokens: 2048,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    });

    const content = message.content[0];
    if (content.type === 'text') {
      return this.formatReviewOutput(content.text, options.prNumber);
    }
    throw new Error('Unexpected response format');
  }

  private buildAnalysisPrompt(options: AnalysisOptions): string {
    let prompt = `Analyze the following code and provide reasoning about its quality, correctness, and improvements:`;
    
    if (options.prNumber) {
      prompt += `\n\nPR #${options.prNumber} in ${options.repo || 'repository'}`;
    }
    
    if (options.files && options.files.length > 0) {
      prompt += `\n\nFiles to analyze: ${options.files.join(', ')}`;
    }
    
    prompt += `\n\nProvide:\n1. Purpose and intent\n2. Code quality assessment\n3. Potential bugs or issues\n4. Suggested improvements\n5. Security considerations`;
    
    return prompt;
  }

  private formatAnalysisOutput(analysis: string): string {
    return `# Code Analysis Report\n\n${analysis}\n\n---\n*Generated by Mindreader Reasoning Engine*`;
  }

  private formatReviewOutput(review: string, prNumber?: string): string {
    const header = prNumber ? `# Code Review for PR #${prNumber}` : '# Code Review';
    return `${header}\n\n${review}\n\n---\n*Generated by Mindreader Review Engine*`;
  }
}
