import { Groq } from 'groq-sdk';

interface ResearchOptions {
  query: string;
  repo?: string;
  context?: string;
}

export class ResearchEngine {
  private client: Groq;

  constructor() {
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
      throw new Error('GROQ_API_KEY environment variable is not set');
    }
    this.client = new Groq({ apiKey });
  }

  async research(options: ResearchOptions): Promise<string> {
    const prompt = this.buildResearchPrompt(options);
    
    const message = await this.client.messages.create({
      model: 'mixtral-8x7b-32768',
      max_tokens: 2048,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    });

    const content = message.content[0];
    if (content.type === 'text') {
      return this.formatResearchOutput(content.text, options.query);
    }
    throw new Error('Unexpected response format');
  }

  private buildResearchPrompt(options: ResearchOptions): string {
    let prompt = `You are a research assistant. Answer the following question thoroughly and provide structured insights:\n\n`;
    prompt += `Query: ${options.query}\n\n`;
    
    if (options.repo) {
      prompt += `Repository context: ${options.repo}\n\n`;
    }
    
    if (options.context) {
      prompt += `Additional context: ${options.context}\n\n`;
    }
    
    prompt += `Please provide:\n`;
    prompt += `1. Direct answer to the query\n`;
    prompt += `2. Key findings and evidence\n`;
    prompt += `3. Related concepts or considerations\n`;
    prompt += `4. Recommendations or next steps\n`;
    prompt += `5. Confidence level and assumptions\n`;
    
    return prompt;
  }

  private formatResearchOutput(research: string, query: string): string {
    return `# Research Report\n\n**Query:** ${query}\n\n${research}\n\n---\n*Generated by Mindreader Research Engine*`;
  }
}
